producto1=input("nombre de producto: ")
precio1=float(input("precio del producto: "))
cantVendido1=int(input("cantidad vendidos: "))
producto2=input("nombre de producto: ")
precio2=float(input("precio del producto: "))
cantVendido2=int(input("cantidad vendidos: "))
producto3=input("nombre de producto: ")
precio3=float(input("precio del producto: "))
cantVendido3=int(input("cantidad vendidos: "))
producto4=input("nombre de producto: ")
precio4=float(input("precio del producto: "))
cantVendido4=int(input("cantidad vendidos: "))
producto5=input("nombre de producto: ")
precio5=float(input("precio del producto: "))
cantVendido5=int(input("cantidad vendidos: "))
totalVenta1=float(precio1*cantVendido1)
totalVenta2=float(precio2*cantVendido2)
totalVenta3=float(precio3*cantVendido3)
totalVenta4=float(precio4*cantVendido4)
totalVenta5=float(precio5*cantVendido5)
total=(totalVenta1+totalVenta2+totalVenta3+totalVenta4+totalVenta5)
print(f"{producto1} - ${totalVenta1}")
print(f"{producto2} - ${totalVenta2}")
print(f"{producto3} - ${totalVenta3}")
print(f"{producto4} - ${totalVenta4}")
print(f"{producto5} - ${totalVenta5}")
print(f"Total de ventas - ${total}")
